name: 'Confucius Debug AI'
description: 'CI fails? Search 6,800+ AI agent bugs instantly (980+ verified fixes). No match? AI fixes it and saves to KB — next person gets it free.'
author: 'washinmura'

branding:
  icon: 'search'
  color: 'orange'

inputs:
  lobster-id:
    description: 'Your Lobster ID (get one free via MCP: claude mcp add confucius-debug --transport http https://api.washinmura.jp/mcp/debug)'
    required: true
  error-log:
    description: 'Custom error text to analyze (if empty, auto-captures from /tmp/*.log files)'
    required: false
    default: ''
  auto-fix:
    description: '[Coming soon] Create a PR with the suggested fix (true/false). Not yet implemented.'
    required: false
    default: 'false'
  comment:
    description: 'Post fix as a PR/issue comment (true/false). Updates existing comment on re-run.'
    required: false
    default: 'true'
  api-url:
    description: 'Confucius Debug API endpoint (default: production)'
    required: false
    default: 'https://api.washinmura.jp/api/v2/debug-ai'
  language:
    description: 'Response language: en, zh, ja'
    required: false
    default: 'en'
  github-token:
    description: 'GitHub token for PR comments (default: github.token)'
    required: false
    default: ${{ github.token }}

outputs:
  status:
    description: 'Result status: knowledge_hit, analyzed, error'
    value: ${{ steps.confucius.outputs.status }}
  fix:
    description: 'The suggested fix (JSON)'
    value: ${{ steps.confucius.outputs.fix }}
  source:
    description: 'Where the fix came from: knowledge_base, sonnet, opus'
    value: ${{ steps.confucius.outputs.source }}
  cost:
    description: 'Cost of this analysis in USD'
    value: ${{ steps.confucius.outputs.cost }}
  entry-id:
    description: 'Knowledge base entry ID (for feedback)'
    value: ${{ steps.confucius.outputs.entry_id }}

runs:
  using: 'composite'
  steps:
    - name: Confucius Debug AI Analysis
      id: confucius
      shell: bash
      env:
        LOBSTER_ID: ${{ inputs.lobster-id }}
        ERROR_LOG: ${{ inputs.error-log }}
        API_URL: ${{ inputs.api-url }}
        LANGUAGE: ${{ inputs.language }}
        AUTO_FIX: ${{ inputs.auto-fix }}
        COMMENT: ${{ inputs.comment }}
        GITHUB_TOKEN: ${{ inputs.github-token }}
      run: |
        bash "${{ github.action_path }}/entrypoint.sh"
